### ISSUE TITLE
Units for speed

### ISSUE THREAD

**Issue by laurentg** [opentraffic/traffic-data-exchange-format#1]
Which units should be used in the output format? I guess SI units (m/s, the standard), as some country use mph vs km/h. It could be nice to specify the unit in the format name (such as averageSpeedMetersPerSeconds, averageSpeedMs, or whatever)

**Comment by kpwebb** [comment]
@laurentg i've struggled with this. My preference is for SI m/s, as all our internal calculations are in meters. But those are really really confusing to users. m/s values are weirdly close enough to km/h for some speeds  that they're easily confused and no one other than physicists (or programers) think in m/s.

So I'm torn on this: km/h probably makes sense for any human readable output, but m/s as our internal number?

**Comment by laurentg** [comment]
Using km/h for default human-readable output seems sensible indeed. As for the unit in the API my preferences goes to SI m/s too, as only developers would look into it anyway.

**Comment by kpwebb** [comment]
Excellent! Let's commit to km/h for all publicly visible/exported units (with a switch in UI for those not fortunate enough to live in metric countries) and SI m/s for all developer oriented APIs and internal storage/variables.

I'm also pausing for a moment of silence for the Mars Orbiter and for SI units: http://en.wikipedia.org/wiki/Mars_Climate_Orbiter
